### ISSUE TITLE
Criação de RestController para listar cliente no EndPoint do serviço ClienteService

### ISSUE THREAD

**Issue by victorvsaraujo** [victoriaaraujo10/helpr#1]

**Comment by soulcode-acad** [comment]
Victor show de trabalho, tudo muito organizado e o código bem limpo, faltou alguns detalhes como etiquetar a entrega para facilitar a vida do revisor e dos testadores. De resto estava perfeito. 

![image](https://user-images.githubusercontent.com/100297907/173059850-3d1f958d-0d20-4d41-a290-c95bdca9dae2.png)

**Comment by victorvsaraujo** [comment]
Bom dia Victor, tudo bem? Eu etiquetei as entregas mas não sei porquê não ficou visível para você.

![image](https://user-images.githubusercontent.com/97119760/173364452-08d653d3-718b-4dfd-9186-46bf0d5c1354.png)

![image](https://user-images.githubusercontent.com/97119760/173364488-284db1a3-f7a5-45c6-b6f8-1bbd50d26dc3.png)

![image](https://user-images.githubusercontent.com/97119760/173364499-7756fdab-3788-4818-9d8b-91528907345c.png)

![image](https://user-images.githubusercontent.com/97119760/173364518-85586216-b9f6-40a5-ba98-2e1d73f5d6a6.png)

![image](https://user-images.githubusercontent.com/97119760/173364534-35cfb8e4-7da2-459e-914d-79bddf20311a.png)
